config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to:"diaries#index"
  post '/diaries/result', to: 'diaries#result'
  
  resources :users, only:[:index] do 
    resources :diaries, only:[:index, :new, :create, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '勉強' },
    { id: 3, name: '仕事' },
    { id: 4, name: '家事' },
    { id: 5, name: '育児' },
    { id: 6, name: '人付き合い' },
    { id: 7, name: 'その他いろいろ' },
  ]
  include ActiveHash::Associations
  has_many :diaries
  
end

app/models/diary.rb
class Diary < ApplicationRecord
  belongs_to  :user
  validates :user, :category_id, :feeling_id, :day, presence: true
  validates :category_id, :feeling_id, numericality: {other_than: 1, message: "は--以外から選択してください"}

  def start_time
    self.day
  end
end

app/models/feeling.rb
class Feeling < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '最高です!!' },
    { id: 3, name: '正直つかれた' },
    { id: 4, name: 'ちょっとしんどい' },
    { id: 5, name: 'つらくて辞めたい' }
  ]
  include ActiveHash::Associations
  has_many :diaries
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname,        presence: true
  validates :password, :password_confirmation, format: { with: (/\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i), message: "は半角英数字混合で入力してください" }
  has_many :diaries
  
  
end

app/models/word1.rb
class Word1 < ActiveHash::Base
  self.data = [
    { id: 1, name: 'さすがっ!' },
    { id: 2, name: 'えらいぞ!!' },
    { id: 3, name: '最高!!!' },
    { id: 4, name: '立派だよー!' },
    { id: 5, name: 'よく頑張りました!!' },
    { id: 6, name: 'えらい!!' },
    { id: 7, name: 'カッコイイ!' },
    { id: 8, name: '素敵です!' },
    { id: 9, name: '素晴らしい!' },
    { id: 10, name: 'コンビニで好きなもの買っちゃおう！' },
    { id: 11, name: '完璧です!!' }
  ]
  include ActiveHash::Associations
  has_many :diaries
  
end

app/models/word2.rb
class Word2 < ActiveHash::Base
  self.data = [
    { id: 1, name: 'よく頑張った!' },
    { id: 2, name: 'えらいぞ!!' },
    { id: 3, name: 'かっこいいよ!!!' },
    { id: 4, name: '立派!' },
    { id: 5, name: 'よく頑張りました!!' },
    { id: 6, name: 'えらい!!' },
    { id: 7, name: 'ゆっくりお風呂に入ろ!' },
    { id: 8, name: 'おつかれさま!' },
    { id: 9, name: '素晴らしい!' },
    { id: 10, name: 'よくやったね!!!' },
    { id: 11, name: '最高!!' }
  ]
  include ActiveHash::Associations
  has_many :diaries
  
end

app/models/word3.rb
class Word3 < ActiveHash::Base
  self.data = [
    { id: 1, name: 'よく頑張りました!' },
    { id: 2, name: 'えらいぞ!!' },
    { id: 3, name: '早く寝よ!!!' },
    { id: 4, name: '立派だったよ!' },
    { id: 5, name: 'ごはんはちゃんと食べて!' },
    { id: 6, name: 'えらい!!' },
    { id: 7, name: 'お疲れ様!!!!' },
    { id: 8, name: 'かっこよかったさ！' },
    { id: 9, name: '頑張ったね！猫ちゃんの動画でもみる?' },
    { id: 10, name: 'そんな日は寝るに限る!' },
    { id: 11, name: 'お疲れ様です!!!' }
  ]
  include ActiveHash::Associations
  has_many :diaries
  
end

app/models/word4.rb
class Word4 < ActiveHash::Base
  self.data = [
    { id: 1, name: '今日1日よくがんばりました!' },
    { id: 2, name: 'えらいぞ!!' },
    { id: 3, name: 'よく頑張った!!!' },
    { id: 4, name: '立派だった！' },
    { id: 5, name: '今日はついてなかっただけ!早く寝よう！' },
    { id: 6, name: 'おやすみできないかな?' },
    { id: 7, name: 'ごはんは食べられそう？' },
    { id: 8, name: 'よく頑張ったね' },
    { id: 9, name: 'お風呂にはいって、寝よう。' },
    { id: 10, name: '次のお休みタイミングで好きなことフルコース!' },
    { id: 11, name: '猫ちゃん動画みよっか?' }
  ]
  include ActiveHash::Associations
  has_many :diaries
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    if current_user
      flash[:notice] = "ログインに成功しました"
      users_path(current_user.id)
    else
      flash[:notice] = "新規登録画面に移動します"
      new_user_session
    end
  end

  
  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :birthday, :email] )
    devise_parameter_sanitizer.permit(:sign_in, keys: [:nickname] )
  end

end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :authenticate_user!,  except: [:index, :result]

  def index
    @diaries = Diary.new
  end

  def result
    @diaries = Diary.new(pasams_result)
    if params[:login]
      render "devise/sessions/new"
    else
    @diaries = Diary.new(pasams_result)
      random_num
      render :result
    end
  end

  def new
    @diary = Diary.new
  end

  def create
    @diaries = Diary.new(pasams_diaries)
    if @diaries.valid?
      @diaries.save
      redirect_to controller: :users, action: :index
    else
      @diary = @diaries
      render "diaries/new"
    end
  end

  def show
    @diary = Diary.find(params[:id])
  end


  private

  def pasams_result
    params.require(:diary).permit(:category_id, :feeling_id)
  end

  def pasams_diaries
    params.require(:diary).permit(:category_id, :feeling_id, :day, :comment).merge(user_id: current_user.id)
  end

  def random_num
    random = Random.new()
      picknum = []
      5.times do
        picknum.push(random.rand(1..11))
      end
      num1 = picknum[1]
      num2 = picknum[2]
      num3 = picknum[3]
      num4 = picknum[4]
      num5 = picknum[4]


        if @diaries.feeling_id == 2
          @message1 = Word1.find([num1])
          @message2 = Word1.find([num2])
          @message3 = Word1.find([num3])
          @message4 = Word1.find([num4])
          @message5 = Word1.find([num5])
        end
        if @diaries.feeling_id == 3
          @message1 = Word2.find([num1])
          @message2 = Word2.find([num2])
          @message3 = Word2.find([num3])
          @message4 = Word2.find([num4])
          @message5 = Word2.find([num5])
        end
        if @diaries.feeling_id == 4
          @message1 = Word3.find([num1])
          @message2 = Word3.find([num2])
          @message3 = Word3.find([num3])
          @message4 = Word3.find([num4])
          @message5 = Word3.find([num5])
        end
        if @diaries.feeling_id == 5
          @message1 = Word4.find([num1])
          @message2 = Word4.find([num2])
          @message3 = Word4.find([num3])
          @message4 = Word4.find([num4])
          @message5 = Word4.find([num5])
        end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @diary = Diary.new
    @user = current_user.id
    @diaries = Diary.all

    @events = []

    @diaries.each do |diary|
      if diary.user_id == @user
        @events << diary
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/diaries/index.html.erb
<div class="bg_pattern ZigZag">
  <div class="container-fluid">


    <div class="top-message ">
      <div class="top-inner">

        <div class="title-wrap text-center">
          <div class="title">
           <h1 class="HOMETAI">HOMETAI</h1>
          </div>
        </div>

  <% unless user_signed_in?%>
    <div class="nav-bar text-center">
      <ul>
        <div class="nav_right">
          <li class="nav_btn"><%= link_to 'ログイン', new_user_session_path%></li>
          <li class="nav_btn"><%= link_to '新規登録', new_user_registration_path%></li>
        </div>
      </ul>
    </div>
  <% end %>

        <div class="top-form">
          <%= form_with model: @diaries, url: diaries_result_path,local: true do |f|%>

            <div class="form-group text-center my-4">

              <div class="set">
                <p class="my-3">今日の頑張ったこと</p>
                <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"form-control form-control-lg", id:"user-category"}) %>
              </div>

              <div class="set">
                 <p class="my-3">今の気分</p>
                 <%= f.collection_select(:feeling_id, Feeling.all, :id, :name, {}, {class:"form-control form-control-lg", id:"user-feel"}) %>
              </div>

                <%# f.submit "ログインして進む", class:"btn btn-border-shadownav_btn", name:"login" %>
                <%= f.submit "OK", class:"btn btn-border-shadownav_btn", name:"no-login" %>


            </div>

          <% end %>
        </div>

      </div>
    </div>


  </div>
</div>

app/views/diaries/new.html.erb
<div class="bg_pattern ZigZag top-messages">
<div class="container">

  <header class="header">
    <div class="inner left">
      <div class="nav">
        <div class="nav_left">
          <h1 class="left_nav">HOMETAI</h1>
        </div>
        <ul>
        <div class="nav_right">
            <li class="nav_btn"><%= link_to 'カレンダー', users_path%></li>
            <li class="nav_btn"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
        </div>
        </ul>
      </div>
    </div>
  </header>

  <div class="diary-form">
    <div class=" text-center mt-4 pt-3">
      <div class="col-md-10 mr-3">

      <%= form_with model: @diary, url: user_diaries_path(current_user.id),local: true do |f|%>
      <%= render 'shared/error_messages', model: f.object %>
              
        <div class="bg-white pt-3 pr-3 pl-3 py-3 first-messages ">

          <div class="set">
            <p class="h5">日付</p>
            <%= f.date_field :day, class:"form-control", class:"form-control", id:"day"%>
          </div>

          <div class="set mt-3">
            <span class="h5">頑張ったこと</span>
            <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"form-control", id:"user-category"}) %>
          </div>

          <div class="set mt-3">
            <span class="h5">今の気分</span>
            <%= f.collection_select(:feeling_id, Feeling.all, :id, :name, {}, {class:"form-control", id:"user-feel"}) %>
          </div>

          <div class="set mt-3">
            <p class="h5">一言メモ</p>
            <%= f.text_field :comment, class:"form-control", size:"50"%>
          </div>

        </div>

        <div class="btn-wrap btn btn-border-shadow font-weight-bold">
          <%= f.submit "カレンダーに保存する", class:"btn", name:"保存" %>
        </div>

      <% end %>

      </div>
    </div>
  </div>

app/views/diaries/result.html.erb
<div class="container">
<div class="bg_pattern ZigZag top-messages">

  <header class="header">
    <div class="inner left">
      <div class="nav">
        <div class="nav_left">
          <h1 class="left_nav">HOMETAI</h1>
        </div>
        <div class="nav_right">
          <ul>
          <% if user_signed_in? %>
            <li class ="nav_btn "><%= link_to 'カレンダー', users_path, class: "users-page" %></li> 
            <li class ="nav_btn"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
          <% else %>
            <li class="list-inline-item"><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
            <li class="list-inline-item"><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
          <% end %>
          </ul>
        </div>
      </div>
    </div>
  </header>

    <div class="messages text-center">
      <div class="first-messages pt-2 pr-2 py-4 pl-2 bg-white">
        <div class="message-title ">
          <h1 >お疲れ様です</h1>
        </div>
       <%#<div class="message">
          <div class="message-content">
            <p>test<br>text</p>
          </div>
        </div>%>
      </div>

      <% if user_signed_in? %>
      <div class="btn-wrap">
        <%= link_to 'カレンダーに移動', new_user_diary_path(current_user.id), class: " btn btn-border-shadow" %>
      </div> 
      <% else %>
      <div class="btn-wrap">
        <%= link_to 'ログインしてカレンダーへ移動', new_user_session_path, class: " btn btn-border-shadow" %>
      </div>
      <% end %>

  <div class="secand-messages center-block">
    <div class="set-word text-center">
        <div class="text-fild">

        <div class="text left">
          <div class="set">
            <% @message1.each do |message| %>
              <%= message.name %>
            <% end %>  
          </div>
        </div>

        <div class="text right">
          <div class="set">
            <% @message2.each do |message| %>
              <%= message.name %>
            <% end %>  
          </div>
        </div>

        <div class="text left">
          <div class="set">
            <% @message3.each do |message| %>
              <%= message.name %>
            <% end %>  
          </div>
        </div>

        <div class="text right">
          <div class="set">
            <% @message4.each do |message| %>
              <%= message.name %>
            <% end %>  
          </div>
        </div>

        <div class="text left">
          <div class="set">
            <% @message5.each do |message| %>
              <%= message.name %>
            <% end %>  
          </div>
        </div>

        </div>
    </div>
  </div>
    
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>HOMETAI</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <div class="container-fluid">
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
  <header class="header">
    <div class="inner left">
      <div class="nav">
        <div class="nav_left">
          <h1 class="left_nav">HOMETAI</h1>
        </div>
        <ul>
        <div class="nav_right">
            <%#= link_to 'マイページ', "#", class: "mypage" %>
            <li class="nav_btn"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
        </div>
        </ul>
      </div>
    </div>
  </header>

app/views/users/index.html.erb
<div class="container">
<div class="bg_pattern ZigZag top-messages">

  <%= render "shared/header" %>

  <div class="text-center">
   <%= link_to '頑張ったことを追加', new_user_diary_path(current_user.id), class: " btn btn-border-shadow" %>
   <%= link_to '褒められる',  root_path, class: " btn btn-border-shadow" %>
  </div>

  <div class="calendar-page col-md-10">
    <div class="bg-white mt-3">
      <%= month_calendar events: @events do |date, events| %>
        <%= date.day %>
        <% events.each do |event|%>
          <div>
            <%=link_to "⭐️", diaries_result_path%>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

</div>
</div>